package com.jadynai.svg.sample.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_arrow extends SVGRenderer {

    public ic_arrow(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(64.0f);
        mHeight = dip2px(64.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 64.0f;
        final float scaleY = h / 64.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(32.0f, 32.0f);
        mPath.rMoveTo(-32.0f, 0.0f);
        mPath.cubicTo(-1.0389503E-15f, 23.516327f, 3.3737204f, 15.371446f, 9.372583f, 9.372583f);
        mPath.cubicTo(15.371446f, 3.3737204f, 23.516327f, 1.5584254E-15f, 32.0f, 0.0f);
        mPath.cubicTo(40.483673f, -1.5584254E-15f, 48.628555f, 3.3737204f, 54.62742f, 9.372583f);
        mPath.cubicTo(60.626278f, 15.371446f, 64.0f, 23.516327f, 64.0f, 32.0f);
        mPath.cubicTo(64.0f, 40.483673f, 60.626278f, 48.628555f, 54.62742f, 54.62742f);
        mPath.cubicTo(48.628555f, 60.626278f, 40.483673f, 64.0f, 32.0f, 64.0f);
        mPath.cubicTo(23.516327f, 64.0f, 15.371446f, 60.626278f, 9.372583f, 54.62742f);
        mPath.cubicTo(3.3737204f, 48.628555f, 1.0389503E-15f, 40.483673f, 0.0f, 32.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-14934492, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(35.5603f, 31.9991f);
        mPath.lineTo(29.0993f, 26.0361f);
        mPath.cubicTo(28.6596f, 25.6342f, 28.6596f, 24.9828f, 29.0993f, 24.5809f);
        mPath.cubicTo(29.3189f, 24.3797f, 29.6071f, 24.2793f, 29.8954f, 24.2793f);
        mPath.cubicTo(30.1836f, 24.2793f, 30.4718f, 24.3797f, 30.6914f, 24.5809f);
        mPath.lineTo(37.9398f, 31.2705f);
        mPath.cubicTo(38.1599f, 31.4717f, 38.2698f, 31.7354f, 38.2695f, 31.9991f);
        mPath.cubicTo(38.2698f, 32.2628f, 38.1599f, 32.5265f, 37.9398f, 32.7277f);
        mPath.lineTo(30.6914f, 39.4173f);
        mPath.cubicTo(30.2523f, 39.8192f, 29.5384f, 39.8192f, 29.0993f, 39.4173f);
        mPath.cubicTo(28.6596f, 39.0154f, 28.6596f, 38.364f, 29.0993f, 37.9621f);
        mPath.lineTo(35.5603f, 31.9991f);
        mPath.close();
        mPath.moveTo(35.5603f, 31.9991f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mRenderPath.setFillType(android.graphics.Path.FillType.EVEN_ODD);
        mFillPaint.setColor(applyAlpha(-1, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}